plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

exclude: ["_backup", "CNAME", "LICENSE.md", "README.md"]

markdown: kramdown
permalink: pretty

host: https://www.sebastianmeier.eu

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      title: "Data-driven Innovation"