plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

markdown: kramdown
permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      title: "Data-driven Innovation"